### ISSUE TITLE
contact info from search call?

### ISSUE THREAD

**Issue by chovy** [brozeph/node-craigslist#14]
Is it possible to add contact info from the search api?

ie: email

**Comment by brozeph** [comment]
@chovy can you provide an example posting? The code attempts to do this, but the flow is tricky within the code - any examples will help.

**Comment by chovy** [comment]
Sorry I mispoke, I meant to say is it possible to get contact info *back* from a search api call. I looked and it looks like recatpcha would be the blocker here to get at the "reply" contact data.

**Comment by blaynem** [comment]
Hey brozeph, I see you send us back the reply url with the information on it. Any chance you'll be updating it to return that also?

**Comment by akigupta131** [comment]
IMO, I don't think that can be possible. Reply URL can be fetched in the details of the listing only.

**Comment by brozeph** [comment]
Closing due to inability to implement at this time...
