### ISSUE TITLE
use proxy with request call?

### ISSUE THREAD

**Issue by chovy** [brozeph/node-craigslist#15]
Can I pass request options to search()? ie: `{ proxy: 'http://xxxx' }`. It would be easy since you're using `request` http lib to merge custom request options into your defaults.

**Comment by brozeph** [comment]
Hi @chovy - this is now implemented... please try specifying `proxy` as an option (either directly to search or when initializing the component for subsequent usage).

**Comment by brozeph** [comment]
Closing as item is now addressed...
