### ISSUE TITLE
url property contains duplicate url inside

### ISSUE THREAD

**Issue by Jaden-Giordano** [brozeph/node-craigslist#24]
https://travis-ci.org/brozeph/node-craigslist/jobs/278743585
`Error: getaddrinfo ENOTFOUND seattle.craigslist.orghttps seattle.craigslist.orghttps:443`

Somehow the url property has a duplicate url inside, for example, `https://atlanta.craigslist.orghttps://atlanta.craigslist.org/atl/cto/d/2006-mercedes-benz-e350-sedan/6277839728.html`.

**Comment by brozeph** [comment]
@Jaden-Giordano - thank you for this issue report! Your PR was helpful as well - I utilized `url-parse` per your suggestion, but I reworked a couple things to pass CI.
