### ISSUE TITLE
No 'Access-Control-Allow-Origin' header present

### ISSUE THREAD

**Issue by kevinliang43** [brozeph/node-craigslist#38]
I am getting an error while trying to search using the `client`:

![image](https://user-images.githubusercontent.com/15353453/76376288-54bc0b80-631e-11ea-9535-5a8a90636af3.png)

while using the following example code from the [documentation](https://www.npmjs.com/package/node-craigslist):

```var
  craigslist = require('node-craigslist'),
  client = new craigslist.Client({
    city : 'seattle'
  });
 
client
  .search('xbox one')
  .then((listings) => {
    // play with listings here...
    listings.forEach((listing) => console.log(listing));
  })
  .catch((err) => {
    console.error(err);
  });  ```


Are there any work-arounds for this?

**Comment by brozeph** [comment]
@kevinliang43, I ran the integration tests (which effectively do the same thing), but did not see an issue. Are you on a network with a proxy or anything that might be interfering with or intercepting the outbound network connection? Do you see this with other network access libraries?

**Comment by kevinliang43** [comment]
Thanks for the quick response.

To my knowledge, I do not believe that I am on a network with a proxy. I've also tested deploying it on a test heroku instance, but ran into the same errors there. I am currently getting around this by using [CORS-Anywhere](https://github.com/Rob--W/cors-anywhere), which seems to solve my problem for now.

**Comment by SocialAnxty** [comment]
Having this same issue

**Comment by SocialAnxty** [comment]
Any idea what could be causing it? Happening from my firebase hosting. Everything else is working fine this is only node module giving me CORS error.

**Comment by brozeph** [comment]
@kevinliang43 - thank you for adding detail on how you worked around the issue! Closing the open issue.
