### ISSUE TITLE
Listing URL from nearby site returns strange values

### ISSUE THREAD

**Issue by tweakdeveloper** [brozeph/node-craigslist#4]
For example, when I receive a listing from New Orleans that was supposed to be from Mobile, it returns a URL like this:

`http://mobile.craigslist.com/http//neworleans.craigslist.com`...

**Comment by tweakdeveloper** [comment]
This code seems to return the correct value:

    var urlRegex = /[a-z]*\.craigslist\.org\/cto\/[0-9]*\.html$/;
    var properUrl = 'http://' + urlRegex.exec(url)[0];

**Comment by jbeuckm** [comment]
Can you do a pull request?

**Comment by tweakdeveloper** [comment]
I actually got my IP blocked on both my home internet and Cloud9. Oops.
