### ISSUE TITLE
Results appear cached after the first request. Possible to still use Proxy?

### ISSUE THREAD

**Issue by DavidLangva** [brozeph/node-craigslist#41]
This package is awesome!

Unfortunately, all my results appear cached after the first request. I've verified this by running the same search on craigslist in the browser. In the browser I see new listings followed by listings that match up with my stale results.

I am using `nocache: true`

My guess is that craigslist is sending me the same results over and over.

I have copied my code into a repl and was able to pull updated results, but again after the first pull, all subsequent pulls brought in the same data.

Here is a link to that repl:
[repl](https://repl.it/repls/LovableNocturnalEntropy#index.js)
Here is a link to the same search on craigslist:
[CL link](https://newyork.craigslist.org/search/sss?query=records&sort=rel&min_price=2&max_price=400
)
**Note:** if you test this, you should run my repl once, see if it matches with craigslist, wait a few minutes for more results to be added to craigslist, and then refresh both the repl and craigslist. results will now be out of sync.

I was hoping sending requests through a proxy would allow me to get fresh results every time.

I noticed from this issue that it was once possible to use a proxy. [proxy issue](https://github.com/brozeph/node-craigslist/issues/15)

Is it possible to get the proxy option back or is there an alternative solution to this issue?

Thank you

**Comment by brozeph** [comment]
@DavidLangva, great request here... when this lib was built, I used an internal abstraction to make requests a bit easier. Since then, I pulled out that abstraction to a different lib (<https://github.com/brozeph/reqlib>), but I haven't implemented the `proxy` feature in that lib just yet. Assigning this to myself as an item!

**Comment by DavidLangva** [comment]
@brozeph awesome! thanks.

If any one else is looking to use `proxy`, I downgraded to version 1.2.2 and it works. However, this will come at the cost of `minPrice` and `maxPrice` not working.

**Comment by brozeph** [comment]
@DavidLangva, I just pushed `v2.2.0` to NPM and the `proxy` feature should now work in the same way that it was implemented in the previous version of this library!
