### ISSUE TITLE
Url for listings in nearby city are wrong.

### ISSUE THREAD

**Issue by nmurrin** [brozeph/node-craigslist#6]
If I have a search query in Chicago and Craigslist displays listings in nearby cities then the url is wrong.  It will end up being something like:

https://chicago.craigslist.com//rockford.craigslist.com/....

Should be

https://rockford.craigslist.com/...

**Comment by brozeph** [comment]
@nmurrin - I've adjusted the code in `v1.0.0` to resolve this issue
