### ISSUE TITLE
baseHost Not Configured for Canadian Cities

### ISSUE THREAD

**Issue by danielstern** [brozeph/node-craigslist#7]
To get this to work for Toronto, I had to change the code like so:

`baseHost = '.craigslist.ca',`

Maybe a flag in options to allow this to be set in a custom manner?

**Comment by stikx2432** [comment]
I just ran into this problem I was thinking the same thing. Maybe adding a domain suffix option for different areas that may require it

**Comment by danielstern** [comment]
@stikx2432 I was able to shim this solution by forking the repo and changing the .com to .ca in the source - works fine!

**Comment by stikx2432** [comment]
I havent forked it. Ito be honest really never got into git or github so im Noob level on github
But i PUT a suffix option. But im having issues with my project. I am parsing all page urls flagged with pictures then storing them i suppose its similar to site scraping im only using Craigslist as tests and practise

**Comment by klvs** [comment]
@danielstern should we add a fall back for .ca, or the other way around?

**Comment by brozeph** [comment]
@danielstern - would you be willing to do a Pull Request back to this repo? I'll rev and push to npm...

**Comment by klvs** [comment]
@danielstern If you link me to a repo that replicates the issue, I'll submit a PR

**Comment by brozeph** [comment]
@danielstern, @klvs and @stikx2432 - in `v1.0.0` I've adjusted the lib to allow `baseHost` to be specified as an option to either the constructor to the search method: [https://github.com/brozeph/node-craigslist#options]

```javascript
const craigslist = require('node-craigslist');

let client = new craigslist.Client({
  city: 'toronto',
  baseHost: 'craigslist.ca'
});

client
  .search('xbox')
  .then((results) => {
    results.forEach((listing) => console.log);
  })
  .catch(console.error);
```

**Comment by danielstern** [comment]
@brozeph Very cool
